routes/web.php
<?php

use App\Keyword;
use App\Faucet;
use App\PaymentProcessor;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', 'RotatorController@index');

Route::patch('faucets/checkFaucetsStatus', [
    'as' => 'checkFaucetsStatus', 'uses' => 'FaucetsController@checkFaucetsStatus'
]);
Route::patch('faucets/{$slug}', [
    'as' => 'faucetLowBalance', 'uses' => 'FaucetsController@faucetLowBalance'
]);
Route::patch('checkFaucetsStatus', 'FaucetsController@checkFaucetsStatus');
Route::get('faucets/progress', 'FaucetsController@progress');
Route::get('/admin/faucets/create', 'FaucetsController@create');
Route::get('/admin/faucets/{slug}/edit', 'FaucetsController@edit');
Route::resource('faucets', 'FaucetsController');
Route::get('users/{userSlug}/faucets', 'FaucetsController@generalUsersIndex');
Route::get('users/{userSlug}/faucets/create', 'FaucetsController@createGeneralUserFaucets');
Route::get('users/{userSlug}/faucets/{faucetSlug}', 'FaucetsController@showGeneralUserFaucet');
Route::get('users/{userSlug}/faucets/{faucetSlug}/edit', 'FaucetsController@editGeneralUserFaucet');
Route::delete('users/{userSlug}/faucets/{faucetSlug}', 'FaucetsController@destroyGeneralUserFaucet');

Route::resource('payment_processors', 'PaymentProcessorsController');
Route::get('/payment_processors', ['as' => 'payment_processors', 'uses' => 'PaymentProcessorsController@index']);
Route::get('/admin/payment_processors/create', 'PaymentProcessorsController@create');
Route::get('/admin/payment_processors/{slug}/edit', 'PaymentProcessorsController@edit');
Route::get('payment_processors/{paymentProcessorSlug}/rotator', 'PaymentProcessorsController@faucets');


Route::resource('main_meta', 'MainMetaController');
Route::get('/admin/main_meta', 'MainMetaController@index');

Route::resource('admin/twitter_config', 'TwitterConfigController');
Route::get('/admin/twitter_config', 'TwitterConfigController@index');

Route::resource('admin/ad_block_config', 'AdBlockController');
Route::get('/admin/ad_block_config', 'AdBlockController@index');

Route::get('admin', ['as' => 'admin', 'uses' => 'AdminController@index']);
Route::get('admin/edit', ['as' => 'admin.edit', 'uses' => 'AdminController@edit']);
Route::patch('admin/update', ['as' => 'admin.update', 'uses' => 'AdminController@update']);
Route::get('admin/overview', 'AdminController@overview');

Route::get('tags', ['as' => 'tags.index', 'uses' => 'KeywordsController@index']);
Route::get('tags/{slug}', ['as' => 'tags.show', 'uses' => 'KeywordsController@show']);

Route::get('data/download', 'DownloadSpreadsheetDataController@index');

Route::get(
    '/data/download/faucets',
    [
        'as' => 'data/download/faucets',
        'uses' => 'DownloadSpreadsheetDataController@getFaucetsData'
    ]
);

Route::get(
    '/data/download/payment_processors',
    [
        'as' => 'data/download/payment_processors',
        'uses' => 'DownloadSpreadsheetDataController@getPaymentProcessorsData'
    ]
);

Route::get(
    '/data/download/faucets_payment_processors',
    [
        'as' => 'data/download/faucets_payment_processors',
        'uses' => 'DownloadSpreadsheetDataController@getFaucetsPaymentProcessorsLinkingData'
    ]
);

Route::get(
    '/data/download/ad_block',
    [
        'as' => 'data/download/ad_block',
        'uses' => 'DownloadSpreadsheetDataController@getAdBlockData'
    ]
);

Route::get(
    '/data/download/main_meta',
    [
        'as' => 'data/download/main_meta',
        'uses' => 'DownloadSpreadsheetDataController@getMainMetaData'
    ]
);

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('sitemap', function () {

    // create new sitemap object
    $sitemap = App::make("sitemap");

    // set cache (key (string), duration in minutes (Carbon|Datetime|int), turn on/off (boolean))
    // by default cache is disabled
    $sitemap->setCache('laravel.sitemap', 15);

    // check if there is cached sitemap and build new only if is not
    if (!$sitemap->isCached()) {
        // add item to the sitemap (url, date, priority, freq)
        $sitemap->add(URL::to('/'), Carbon::now(), '1.0', 'daily');
        $sitemap->add(URL::to('/faucets'), Carbon::now(), '1.0', 'daily');
        $sitemap->add(URL::to('/payment_processors'), Carbon::now(), '1.0', 'daily');

        // get all faucets from db
        $faucets = Faucet::orderBy('name', 'asc')->get();

        // add every post to the sitemap
        foreach ($faucets as $f) {
            $url = URL::to("/faucets/" . $f->slug);
            $sitemap->add($url, $f->updated_at, '1.0', 'daily');
        }

        $payment_processors = PaymentProcessor::orderBy('name', 'asc')->get();


        foreach ($payment_processors as $p) {
            $url = URL::to("/payment_processors/" . $p->slug);
            $sitemap->add($url, $p->updated_at, '1.0', 'daily');

            $rotator = URL::to("/payment_processors/" . $p->slug . '/rotator');
            $sitemap->add($rotator, $p->updated_at, '1.0', 'daily');
        }

        $tags = Keyword::orderBy('keyword', 'asc')->get();

        foreach($tags as $t){
            $sitemap->add(
                URL::to('/tags/' . $t->slug),
                $t->updated_at,
                '1.0',
                'daily'
            );
        }
    }

    // show your sitemap (options: 'xml' (default), 'html', 'txt', 'ror-rss', 'ror-rdf')
    return $sitemap->render('xml');
});

Route::get('feed', function () {

    // create new feed
    $feed = App::make("feed");

    // cache the feed for 60 minutes (second parameter is optional)
    $feed->setCache(60, 'laravelFeedKey');

    // check if there is cached feed and build new only if is not
    //if (!$feed->isCached()) {
    // creating rss feed with our most recent 20 posts
    $faucets =  $faucets = Faucet::orderBy('name', 'asc')->get();

    // set your feed's title, description, link, pubdate and language
    $feed->title = 'FreeBTC.Website Bitcoin Faucet Rotator Feed';
    $feed->description = 'The Atom/RSS feed which shows the latest bitcoin faucets.';
    $feed->link = URL::to('feed');
    $feed->setDateFormat('datetime'); // 'datetime', 'timestamp' or 'carbon'
    $feed->pubdate = $faucets[0]->created_at;
    $feed->lang = 'en';
    $feed->setShortening(true); // true or false
    $feed->setTextLimit(100); // maximum length of description text

    foreach ($faucets as $faucet) {
        $title = isset($faucet->meta_title) == true ? $faucet->meta_title : $faucet->name;

        // set item's title, author, url, pubdate, description and content
        $feed->add(
            $title,
            'FreeBTC.Website Bitcoin Faucet Rotator',
            URL::to('/faucets/' . $faucet->slug),
            $faucet->created_at,
            str_replace('&', ' and ', $faucet->meta_description),
            $faucet->meta_description
        );
    }

    $payment_processors = PaymentProcessor::orderBy('name', 'asc')->get();

    foreach ($payment_processors as $p) {
        $title = isset($p->meta_title) == true ? $p->meta_title : $p->name;

        // set item's title, author, url, pubdate, description and content
        $feed->add(
            $title,
            $p->name,
            URL::to('/payment_processors/' . $p->slug),
            $p->created_at,
            str_replace('&', ' and ', $p->meta_description),
            $p->meta_description
        );

        $rotator = URL::to("/payment_processors/" . $p->slug . '/rotator');
        $feed->add(
            $title,
            $p->name,
            $rotator,
            $p->created_at,
            $p->name . ' Faucet Rotator',
            'Earn free bitcoins from faucets that use "' . $p->name . '" as a payment processor.'
        );
    }

    $tags = Keyword::orderBy('keyword', 'asc')->get();

    foreach($tags as $t){
        $feed->add(
            'Tag - ' . $t->keyword,
            $t->keyword,
            URL::to('/tags/' . $t->slug),
            $t->created_at,
            'Tag - ' . $t->keyword . ' | FreeBTC.website',
            'This page shows information about the "' . $t->keyword . '" tag. There are ' .
            count($t->faucets()->get()) . ' faucets, and ' . count($t->paymentProcessors()->get()) .
            ' payment processors, that use this tag.'
        );
    }

    $feed->setView('pages.rss');
    return $feed->render('rss');

    //}
});

Route::get('500', function () {
    abort(500);
});

app/Faucet.php
<?php namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Laravel\Scout\Searchable;

/**
 * Class Faucet
 *
 *
 * A model class for a faucet.
 *
 * @author Rob Attfield <emailme@robertattfield.com> <http://www.robertattfield.com>
 * @package App
 */
class Faucet extends AppModel
{

	use Sluggable, Searchable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'faucets';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name',
                           'url',
                           'interval_minutes',
                           'min_payout',
                           'max_payout',
                           'has_ref_program',
                           'ref_payout_percent',
                           'comments',
                           'is_paused',
                           'meta_title',
                           'meta_description',
                           'meta_keywords',
                           'has_low_balance'];

    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     * A method defining the relationship between
     * a faucet and payment processors.
     */
    public function paymentProcessors()
    {
        return $this->belongsToMany(PaymentProcessor::class, 'faucet_payment_processor')->orderBy('name');
    }

    /**
     * A method defining the relationship between
     * a faucet and users.
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'referral_info');
    }

    /**
     * Get linked keywords.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function keywords()
    {
        return $this->belongsToMany(Keyword::class, 'faucets_keywords');
    }

    /**
     * A method to tell user if a faucet
     * has a referral program or not, in
     * a readable format.
     * @return string
     */
    public function hasRefProgram()
    {
        if ($this->attributes['has_ref_program']) {
            return 'Yes';
        }
        return 'No';
    }
    /**
     * A method to tell user if a faucet
     * is paused or not, in
     * a readable format.
     * @return string
     */
    public function status()
    {
        if ($this->attributes['is_paused']) {
            return 'Paused';
        }
        return 'Active';
    }

    public function lowBalanceStatus()
    {
        if ($this->attributes['has_low_balance'] == true) {
            return 'Yes';
        }
        return 'No';
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

resources/views/faucets/create.blade.php
@extends('app')

@section('content')
    <h1 class="page-heading">Create a new faucet</h1>

    @include('faucets/partials/_errors')

    {!! Form::open(['route' => 'faucets.store','class' => 'form-horizontal']) !!}
        @include('faucets/partials/_form')
    {!! Form::close() !!}
@endsection

resources/views/faucets/edit.blade.php
@extends('app')

@section('content')
    <h1 class="page-heading">Edit '{{ $faucet->name }}'</h1>

    @include('faucets/partials/_errors')

    {!! Form::model( $faucet, ['method' => 'PATCH', 'route' => ['faucets.update', $faucet->slug],'class' => 'form-horizontal']) !!}
    @include('faucets/partials/_form')
    {!! Form::close() !!}
@endsection

resources/views/faucets/index.blade.php
@extends('app')

@section('title', 'List of Bitcoin Faucets (' . count($faucets).') | FreeBTC.website')

@section('description', 'This page lists all bitcoin faucets currently on the system, with sortable columns. There are ' . count($faucets) . ' faucets listed.')

@section('keywords', 'Free Bitcoins, Bitcoin Faucets, Get Free Bitcoins, Satoshis, Free BTC Website')

@section('content')
    <h1 class="page-heading">Current Faucets</h1>
    @if(\App\Helpers\WebsiteMeta\WebsiteMeta::disqusShortName())
        <p id="comments"><small><a href="#disqus_thread">See comments</a></small></p>
    @endif
    @include('partials.ads')
    @include('faucets/partials/_session_messages')
    @if(Auth::check())
        <div class="alert alert-info">
            <p><i class="fa fa-info-circle fa-2x space-right"></i>Tags are created when creating and editing faucets.</p>
        </div>
    @endif
    <div class="table-responsive">
        <table class="table table-striped bordered tablesorter" id="faucets_table">
            <thead>
                <th>Faucet Name</th>
                <th>Interval (minutes)</th>
                <th>Minimum Payout (satoshis)</th>
                <th>Maximum Payout (satoshis)</th>
                <th>Payment Processor/s</th>
                <th>Referral Program?</th>
                <th>Ref. Payout %</th>
                <th>Tags</th>
            </thead>
            <tbody>
            @foreach($faucets as $faucet)
                <tr>
                    <td>
                        {!! link_to_route('faucets.show', $faucet->name, array($faucet->slug), ['title' => $faucet->name]) !!}
                        @if(Auth::check())
                            <br><a class="btn btn-primary btn-width-small" href="/faucets/{{ $faucet->slug}}/edit/">
                                <span class="button-font-small">Edit</span>
                            </a>
                            <br><br>
                            <a class="btn btn-primary btn-width-small" id="confirm" data-toggle="modal" href="#" data-target="#delFaucet{{ $faucet->slug}}" data-id="{{ $faucet->slug }}">
                                <span class="button-font-small">Delete</span>
                            </a>
                            <?php $slug = $faucet->slug ?>
                            @include('faucets/partials/_modal_delete_faucet')
                        @endif

                    </td>
                    <td>{{ $faucet->interval_minutes }}</td>
                    <td>{{ $faucet->min_payout }}</td>
                    <td>{{ $faucet->max_payout }}</td>
                    <td>
                        <ul class="faucet-payment-processors">
                            @foreach($faucet->paymentProcessors as $paymentProcessor)
                                <li>{!! link_to_route('payment_processors.show', $paymentProcessor->name, [$paymentProcessor->slug]) !!}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{ $faucet->hasRefProgram() }}</td>
                    <td>{{ $faucet->ref_payout_percent }}</td>
                    <td>
                        @if(count($faucet->keywords()->get()) > 0)
                            <ul>
                                @foreach($faucet->keywords()->orderBy('keyword')->get() as $tag)
                                    <li>
                                        {!! link_to_route('tags.show', $tag->keyword, ['slug' => $tag->slug]) !!}
                                    </li>
                                @endforeach
                            </ul>
                        @else
                            <ul>
                                <li>There are no tags for this faucet.</li>
                            </ul>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    @if(\App\Helpers\WebsiteMeta\WebsiteMeta::disqusShortName())
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            var disqus_shortname = '{{ \App\Helpers\WebsiteMeta\WebsiteMeta::disqusShortName() }}';
            var disqus_identifier = 'list-of-faucets';

            (function() {
                var dsq = document.createElement('script');
                dsq.type = 'text/javascript';
                dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] ||
                document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>
            Please enable JavaScript to view the
            <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
        </noscript>
        <a href="http://disqus.com" class="dsq-brlink">
            comments powered by <span class="logo-disqus">Disqus</span>
        </a>
    @endif
    <br><br>

@endsection

@section('google_analytics')
    @include('partials.google_analytics')
@stop

resources/views/faucets/show.blade.php
@extends('app')

@if($faucet)
@section('title', $faucet->meta_title)

@section('description', $faucet->meta_description)

@section('keywords', $faucet->meta_keywords)

@section('content')
    <h1 class="page-heading">{{ $faucet->name }}</h1>
    @if(\App\Helpers\WebsiteMeta\WebsiteMeta::disqusShortName())
        <p id="comments"><small><a href="#disqus_thread">See comments</a></small></p>
    @endif
    @if (Auth::user())

        <script>
            window.csrfToken = '<?php echo csrf_token(); ?>';
        </script>
        <p>
            <a class="btn btn-primary btn-width" href="/faucets/{{ $faucet->slug }}/edit/">
                <span class="fa fa-edit fa-1x space-right"></span><span class="button-font-size">Edit</span>
            </a>
            <a class="btn btn-primary btn-width" id="confirm" data-toggle="modal" href="#" data-target="#delFaucet{{ $faucet->slug}}" data-id="{{ $faucet->slug }}">
                <span class="fa fa-trash fa-1x space-right"></span>
                <span class="button-font-size">Delete</span>
            </a>
        </p>

        @if(Auth::check())
            @include('faucets/partials/_modal_delete_faucet')
        @endif
    @endif
    <p>{!! link_to('faucets', '&laquo; Back to list of faucets') !!}</p>
    @if (Session::has('success_message'))
        <div class="alert alert-success">
            <span class="fa fa-thumbs-o-up fa-2x space-right"></span>
            {{ Session::get('success_message') }}
        </div>
    @endif
    @if (Session::has('success_message_update_faucet_low_balance_status'))
        <div class="alert alert-success">
            <span class="fa fa-thumbs-o-up fa-2x space-right"></span>
            {{ Session::get('success_message_update_faucet_low_balance_status') }}
        </div>
    @endif
    @include('partials.ads')
    <div class="table-responsive">
        <table class="table table-striped table bordered">
            <thead>
                <th>Faucet URL</th>
                <th>Interval (minutes)</th>
                <th>Minimum Payout (satoshis)</th>
                <th>Maximum Payout (satoshis)</th>
                <th>Payment Processor/s</th>
                <th>Referral Program?</th>
                <th>Ref. Payout %</th>
                <th>Comments</th>
                <th>Status</th>
                <th>Low Balance <br><small>(less than 10,000 SAT)</small></th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {!! link_to($faucet->url, $faucet->name, ['target' => 'blank', 'title' => $faucet->name]) !!}
                    </td>
                    <td>{{ $faucet->interval_minutes }}</td>
                    <td>{{ $faucet->min_payout }}</td>
                    <td>{{ $faucet->max_payout }}</td>
                    <td>
                    @if($faucet->paymentProcessors)
                        @if(count($faucet->paymentProcessors) == 0)
                            None. Please add one (or more) for this faucet
                        @else
                            <ul class="faucet-payment-processors">
                            @foreach($faucet->paymentProcessors as $paymentProcessor)
                                <li>{!! link_to('payment_processors/' . $paymentProcessor->slug, $paymentProcessor->name, ['target' => 'blank', 'title' => $paymentProcessor->name]) !!}</li>
                            @endforeach
                            </ul>
                        @endif
                    @endif

                    </td>
                    <td>{{ $faucet->hasRefProgram() }}</td>
                    <td>{{ $faucet->ref_payout_percent }}</td>
                    <td>{{ $faucet->comments }}</td>
                    <td>{{ $faucet->status() }}</td>
                    <td>{{ $faucet->lowBalanceStatus() }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div>
        @if(count($faucet->keywords()->get()) > 0)
        <p>Tags:
            @for($i = 0; $i < count($faucet->keywords()->get()); $i++)
                {!!
                    link_to_route('tags.show', $faucet->keywords()->get()[$i]->keyword, [$faucet->keywords()->get()[$i]->slug]) .
                    ($i != count($faucet->keywords()->get()) - 1 ? ", " : ".")
                !!}
            @endfor
        </p>
        @endif
    </div>
    @if($faucet->is_paused == false)
        <iframe sandbox="allow-forms allow-scripts allow-pointer-lock allow-same-origin" src="{{ $faucet->url }}" id="faucet-iframe"></iframe>
    @else
        <p>This faucet has been paused from showing in rotation.</p>

        @if(Auth::user())
            <p>You can {!! link_to('/faucets/' . $faucet->slug . '/edit', 'edit this faucet') !!} to re-enable it in rotation.</p>
        @else
            <p>Please contact the administrator if you would like this faucet re-enabled.</p>
        @endif
    @endif

    <hr>
        @include('faucets.partials.disqus')
    <hr>
@endsection

@section('google_analytics')
    @include('partials.google_analytics')
@stop
@endif